USE [OMECH_PROD]
GO
/****** Object:  StoredProcedure [dbo].[DISP_PO_AUTO_MAP]    Script Date: 29-07-2025 07:08:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- DISP_PO_AUTO_MAP '32,33',1
ALTER PROCEDURE [dbo].[DISP_PO_AUTO_MAP]
    @SCHEDULE_SRNOS NVARCHAR(MAX),
    @USER_SRNO INT
AS
BEGIN
-- Create a temporary table to hold the schedule serial numbers
    DECLARE @TempScheduleSrnos TABLE (SCHEDULE_SRNO INT);
    
    -- Parse the comma-separated list of SCHEDULE_SRNOS
    INSERT INTO @TempScheduleSrnos (SCHEDULE_SRNO)
    SELECT value FROM STRING_SPLIT(@SCHEDULE_SRNOS, ',');
    
    -- Group POs by thickness, grade, and OD
    SELECT 
        G.GRADE,
        G.GRADE_SRNO,
        T.THICKNESS,
        T.THICKNESS_SRNO,
        O.OD,
        O.OD_SRNO,
        SM.ITEM_TYPE,
		SM.PARTY_NAME,
		SM.PO_NUMBER,
		SUM(CASE WHEN SM.ITEM_TYPE = 'PIPE' THEN ISNULL(SD.QUANTITY, 0) ELSE 0 END) AS PIPE_QTY,
        SUM(CASE WHEN SM.ITEM_TYPE IN ('COIL', 'SHEET') THEN ISNULL(SD.WEIGHT_KG, 0) ELSE 0 END) AS COIL_SHEET_WEIGHT,
        STRING_AGG(CAST(SM.SCHEDULE_SRNO AS VARCHAR), ',') AS SCHEDULE_SRNOS,
        STRING_AGG(CAST(SD.SCHEDULE_DT_SRNO AS VARCHAR), ',') AS SCHEDULE_DT_SRNOS
    FROM SCHEDULE_DETAIL SD
    INNER JOIN SCHEDULE_MASTER SM ON SD.SCHEDULE_SRNO = SM.SCHEDULE_SRNO
    INNER JOIN M_GRADE G ON SD.GRADE_SRNO = G.GRADE_SRNO
    INNER JOIN M_THICKNESS T ON SD.THICKNESS_SRNO = T.THICKNESS_SRNO
    LEFT JOIN M_OD O ON SD.OD_SRNO = O.OD_SRNO
    WHERE 
        SM.SCHEDULE_SRNO IN (SELECT SCHEDULE_SRNO FROM @TempScheduleSrnos)
        AND SD.DEL_FLAG = 0
        AND SM.DEL_FLAG = 0
        --AND SD.STATUS_SRO = 11 -- Pending status
    GROUP BY 
        G.GRADE,
        G.GRADE_SRNO,
        T.THICKNESS,
        T.THICKNESS_SRNO,
        O.OD,
        O.OD_SRNO,
        SM.ITEM_TYPE,
		SM.PARTY_NAME,
		SM.PO_NUMBER
    HAVING 
        COUNT(*) > 0;
	 END

------------------------------
GOUSE [OMECH_PROD]
GO
/****** Object:  StoredProcedure [dbo].[DISP_SCHEDULE]    Script Date: 29-07-2025 07:19:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER   PROCEDURE [dbo].[DISP_SCHEDULE]
    @SCHEDULE_SRNO INT,
    @USER_SRNO INT
AS
BEGIN
    SET NOCOUNT ON;

    -- 1. Fetch master data
    SELECT 
        SM.SCHEDULE_SRNO,
        SM.PARTY_NAME,
        SM.PO_NUMBER,
        SM.SCHEDULE_DATE,
        SM.ESTIMATED_DELIVERY_DATE,
        SM.STATUS_SRNO,
		SM.ITEM_TYPE,
        SM.REMARKS
    FROM SCHEDULE_MASTER SM
    WHERE SM.SCHEDULE_SRNO = @SCHEDULE_SRNO;

    -- 2. Fetch related detail rows
    SELECT 
        SD.SCHEDULE_DT_SRNO,
        SD.SCHEDULE_SRNO,
        SD.OD_SRNO,
        SD.THICKNESS_SRNO,
        SD.GRADE_SRNO,
        SD.LENGTH,
        SD.QUANTITY,
        SD.STATUS_SRNO,
		SD.WEIGHT_PER_QTY,
		SD.WIDTH,
		SD.BREADTH,
		SD.WEIGHT_KG
		
    FROM SCHEDULE_DETAIL SD
    WHERE SD.SCHEDULE_SRNO = @SCHEDULE_SRNO;
END
-----------------------------------------------
G0
USE [OMECH_PROD]
GO
/****** Object:  StoredProcedure [dbo].[DT_SCHEDULE]    Script Date: 29-07-2025 07:20:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--DT_SCHEDULE 'PIPE',NULL,13,NULL,NULL,NULL,NULL,0
ALTER   PROCEDURE [dbo].[DT_SCHEDULE]
    @ITEM_TYPE NVARCHAR(20) = NULL,
    @PARTY_NAME NVARCHAR(100) = NULL,
    @STATUS_SRNO INT = NULL,
    @ENTRY_DATE_FROM DATE = NULL,
    @ENTRY_DATE_TO DATE = NULL,
    @DELIVERY_DATE_FROM DATE = NULL,
    @DELIVERY_DATE_TO DATE = NULL,
    @USER_SRNO NUMERIC(18,0)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        SM.SCHEDULE_SRNO,
        SM.PARTY_NAME,
        SM.ITEM_TYPE,
        SM.PO_NUMBER,
		dbo.FN_FMT_DATE(SM.SCHEDULE_DATE) AS SCHEDULE_DATE,
		dbo.FN_FMT_DATE(SM.ESTIMATED_DELIVERY_DATE) AS ESTIMATED_DELIVERY_DATE,
        SM.REMARKS,
        MS.STATUS_NAME,
		SM.STATUS_SRNO,
        SUM(SD.QUANTITY) AS T_ORDER_QTY,
        CASE 
            WHEN SM.ITEM_TYPE = 'PIPE' THEN SUM(SD.QUANTITY * SD.WEIGHT_PER_QTY)
            ELSE SUM(SD.WEIGHT_KG)
        END AS T_ORDER_WEIGHT,
		CASE 
			WHEN DATEDIFF(DAY, GETDATE(), SM.ESTIMATED_DELIVERY_DATE) BETWEEN 0 AND 7 THEN 'Y'
			ELSE 'N'
		END AS IS_URGENT_DELIVERY

    FROM SCHEDULE_MASTER SM
        INNER JOIN SCHEDULE_DETAIL SD ON SD.SCHEDULE_SRNO = SM.SCHEDULE_SRNO
        LEFT OUTER JOIN M_STATUS MS ON MS.STATUS_SRNO = SM.STATUS_SRNO
    WHERE 
        SM.DEL_FLAG = 0
        AND (@ITEM_TYPE IS NULL OR SM.ITEM_TYPE = @ITEM_TYPE)
        AND (@PARTY_NAME IS NULL OR SM.PARTY_NAME LIKE '%' + @PARTY_NAME + '%')
		AND (@STATUS_SRNO IS NULL OR SM.STATUS_SRNO = @STATUS_SRNO)
        AND (@ENTRY_DATE_FROM IS NULL OR SM.SCHEDULE_DATE >= @ENTRY_DATE_FROM)
        AND (@ENTRY_DATE_TO IS NULL OR SM.SCHEDULE_DATE <= @ENTRY_DATE_TO)
        AND (@DELIVERY_DATE_FROM IS NULL OR SM.ESTIMATED_DELIVERY_DATE >= @DELIVERY_DATE_FROM)
        AND (@DELIVERY_DATE_TO IS NULL OR SM.ESTIMATED_DELIVERY_DATE <= @DELIVERY_DATE_TO)
    GROUP BY
        SM.SCHEDULE_SRNO,
        SM.PARTY_NAME,
        SM.ITEM_TYPE,
        SM.PO_NUMBER,
        SM.SCHEDULE_DATE,
        SM.ESTIMATED_DELIVERY_DATE,
        SM.REMARKS,
        MS.STATUS_NAME,
		SM.STATUS_SRNO
    ORDER BY SM.SCHEDULE_SRNO DESC
END
-------------------------------------
GO
USE [OMECH_PROD]
GO
/****** Object:  StoredProcedure [dbo].[GET_INV_STATUS_SCHEDULE_WISE]    Script Date: 29-07-2025 07:23:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- GET_INV_STATUS_SCHEDULE_WISE 2,6,6,150,500,120,1
ALTER   PROCEDURE [dbo].[GET_INV_STATUS_SCHEDULE_WISE]
@GRADE_SRNO NUMERIC(18,0),
@THICKNESS_SRNO NUMERIC(18,0),
@OD_SRNO NUMERIC(18,0),

@PR_LENGTH NUMERIC(18,0),
@PR_PRICE NUMERIC(18,0), 
@PR_QUANTITY NUMERIC(18,0),
@USER_SRNO NUMERIC(18,0)

AS
BEGIN
    SET NOCOUNT ON;
	---------------------------------------
	--Global Declareation start
		Declare @OD	DECIMAL(10,2) ,@THICKNESS	DECIMAL(10,2), @GRADE DECIMAL(10,2)
		SELECT @GRADE= GRADE FROM M_GRADE WHERE GRADE_SRNO = @GRADE_SRNO
		SELECT @OD= OD FROM M_OD WHERE OD_SRNO = @OD_SRNO
		SELECT @THICKNESS= THICKNESS FROM M_THICKNESS WHERE THICKNESS_SRNO = @THICKNESS_SRNO
	--Global Declareation End

    SELECT 
		P.PR_INV_SRNO,
		P.PR_SRNO,
        PM.PR_NAME, 
        PM.PR_LENGTH AS PIPE_LENGTH, 
        --P.C_LOCATION,
        P.AVAILABLE_QUANTITY,
        PM.PR_WEIGHT,
        PM.PR_WEIGHT * P.AVAILABLE_QUANTITY AS T_PR_WEIGHT,
		MG.GRADE,
		MT.THICKNESS,
		MO.OD,
		MV.VENDOR_NAME AS C_LOCATION,
			
		FLOOR(CAST(PM.PR_LENGTH AS DECIMAL(10,2)) / NULLIF(CAST(@PR_LENGTH AS DECIMAL(10,2)), 0)) AS QUANTITY_PER_PIPE,

		FLOOR(CAST(PM.PR_LENGTH AS DECIMAL(10,2)) / NULLIF(CAST(@PR_LENGTH AS DECIMAL(10,2)), 0)) *  P.AVAILABLE_QUANTITY AS TOTAL_QUANTITY_PER_PIPE,

		FLOOR(CAST(PM.PR_LENGTH AS DECIMAL(10,2)) % NULLIF(CAST(@PR_LENGTH AS DECIMAL(10,2)), 0)) AS END_PIECE_QUANTITY_PER_PIPE,

		FLOOR(CAST(PM.PR_LENGTH AS DECIMAL(10,2)) % NULLIF(CAST(@PR_LENGTH AS DECIMAL(10,2)), 0)) *  P.AVAILABLE_QUANTITY AS TOTAL_END_PIECE_QUANTITY_PER_PIPE

--		--FLOOR(PM.PR_LENGTH / NULLIF(@PR_LENGTH, 0)) * P.AVAILABLE_QUANTITY AS TOTAL_PRODUCTION_QUANTITY,
--FLOOR(CAST(PM.PR_LENGTH AS DECIMAL(10,2)) / NULLIF(CAST(@PR_LENGTH AS DECIMAL(10,2)), 0)) * P.AVAILABLE_QUANTITY AS TOTAL_PRODUCTION_QUANTITY,
--(CAST(PM.PR_LENGTH AS INT) % NULLIF(CAST(@PR_LENGTH AS INT), 0)) * P.AVAILABLE_QUANTITY AS REMAINING_END_PIECES,



		--(CAST(PM.PR_LENGTH AS DECIMAL(10,2)) / NULLIF(@PR_LENGTH, 0)) * P.AVAILABLE_QUANTITY AS TOTAL_PRODUCTION_QUANTITY,
		--(CAST(PM.PR_LENGTH AS INT) % NULLIF(@PR_LENGTH, 0)) * P.AVAILABLE_QUANTITY AS REMAINING_END_PIECES,





		
    FROM PIPE_INVENTORY P
		INNER JOIN PR_MASTER PM ON PM.PR_SRNO = P.PR_SRNO
		INNER JOIN M_GRADE MG ON PM.GRADE_SRNO = MG.GRADE_SRNO
		INNER JOIN M_THICKNESS MT ON PM.THICKNESS_SRNO = MT.THICKNESS_SRNO
		INNER JOIN M_OD MO ON PM.OD_SRNO = MO.OD_SRNO
		INNER JOIN M_VENDORS MV ON P.C_LOCATION = MV.VENDOR_SRNO
   WHERE 
	P.DEL_FLAG	= 0
	AND P.AVAILABLE_QUANTITY > 0
    --(@PR_SRNO IS NULL OR PM.PR_SRNO = @PR_SRNO)
	AND (@GRADE_SRNO IS NULL OR PM.GRADE_SRNO = @GRADE_SRNO)
	AND (@THICKNESS_SRNO IS NULL OR PM.THICKNESS_SRNO = @THICKNESS_SRNO)
	AND (@OD_SRNO IS NULL OR PM.OD_SRNO= @OD_SRNO)
	--AND (@PR_LENGTH IS NULL OR PM.PR_LENGTH = @PR_LENGTH)



	------------------------------------------------------------------
	SET NOCOUNT ON;

    DECLARE @RequiredWidth DECIMAL(10,2),  @WIDTH_VARIATION INT  = 3
	
    SET @RequiredWidth = @OD * PI()


    -- ±5 mm tolerance
    DECLARE @TempResult TABLE (
    MATERIAL_SRNO INT,
    SLITTING_SRNO INT,
    CHALLAN_NO NVARCHAR(15),
    GRADE NVARCHAR(10),
    THICKNESS DECIMAL(18,2),
    BALANCE_WIDTH DECIMAL(18,2),
    BALANCE_WEIGHT DECIMAL(18,2),
    STATUS_NAME NVARCHAR(50),
    C_LOCATION NVARCHAR(100),
    COIL_TYPE_FLAG NVARCHAR(1) NOT NULL
);


INSERT INTO @TempResult
        SELECT 
            RM.MATERIAL_SRNO,
            0 AS SLITTING_SRNO,
            RM.CHALLAN_NO,
            MG.GRADE,
            MT.THICKNESS,
            RM.MATERIAL_WIDTH - ISNULL(FN.SLITTED_WIDTH, 0) - ISNULL(RM.MATERIAL_SCRAP, 0) AS BALANCE_WIDTH,
			RM.MATERIAL_WEIGHT - ISNULL(FN.SLITTED_WEIGHT, 0) - ISNULL(RM.MATERIAL_SCRAP_WEIGHT, 0) AS BALANCE_WEIGHT,
            --((RM.MATERIAL_WIDTH - ISNULL(FN.SLITTED_WIDTH, 0) - ISNULL(RM.MATERIAL_SCRAP, 0)) / RM.MATERIAL_WIDTH) * RM.MATERIAL_WEIGHT AS BALANCE_WEIGHT,
            MS.STATUS_NAME, 
            MV.VENDOR_NAME AS C_LOCATION,
            'M' AS COIL_TYPE_FLAG
        FROM RAW_MATERIALS RM WITH (NOLOCK)
        INNER JOIN M_STATUS MS ON RM.MATERIAL_STATUS_SRNO = MS.STATUS_SRNO
        INNER JOIN M_VENDORS MV ON RM.C_LOCATION = MV.VENDOR_SRNO
        INNER JOIN M_GRADE MG ON RM.MATERIAL_GRADE_SRNO = MG.GRADE_SRNO
        INNER JOIN M_THICKNESS MT ON RM.MATERIAL_THICKNESS_SRNO = MT.THICKNESS_SRNO
        --CROSS APPLY (SELECT dbo.FN_GET_SLITTED_WIDTH(1, RM.MATERIAL_SRNO) AS SLITTED_WIDTH) AS FN
		CROSS APPLY dbo.FN_GET_SLITTED_DATA(1, RM.MATERIAL_SRNO) AS FN
        WHERE 
            RM.DEL_FLAG = 0
            AND RM.MATERIAL_STATUS_SRNO IN (4,5)
            AND (RM.MATERIAL_GRADE_SRNO = @GRADE_SRNO)
            AND (RM.MATERIAL_THICKNESS_SRNO = @THICKNESS_SRNO)
            --AND (@C_LOCATION IS NULL OR RM.C_LOCATION = @C_LOCATION)
            AND ((RM.MATERIAL_WIDTH - ISNULL(FN.SLITTED_WIDTH, 0) - ISNULL(RM.MATERIAL_SCRAP, 0)) BETWEEN (@RequiredWidth - @WIDTH_VARIATION) AND (@RequiredWidth + @WIDTH_VARIATION))


INSERT INTO @TempResult
        SELECT 
            SP.MATERIAL_SRNO,
            SP.SLITTING_SRNO,
            RM.CHALLAN_NO,
            MG.GRADE,
            MT.THICKNESS,
            SP.SLITTING_WIDTH - ISNULL(FN.SLITTED_WIDTH, 0) - ISNULL(SP.SLITTING_SCRAP, 0) AS BALANCE_WIDTH,
            SP.SLITTING_WEIGHT - ISNULL(FN.SLITTED_WEIGHT, 0) - ISNULL(SP.SLITTING_SCRAP_WEIGHT, 0) AS BALANCE_WEIGHT,
            --((SP.SLITTING_WIDTH - ISNULL(FN.SLITTED_WIDTH, 0) - ISNULL(SP.SLITTING_SCRAP, 0)) / SP.SLITTING_WIDTH) * SP.SLITTING_WEIGHT AS BALANCE_WEIGHT,
            MS.STATUS_NAME, 
            MV.VENDOR_NAME AS C_LOCATION,
            CASE WHEN SP.IS_SLITTED = 1 THEN 'S' ELSE 'P' END AS COIL_TYPE_FLAG
        FROM SLITTING_PROCESSES SP WITH (NOLOCK)
        INNER JOIN RAW_MATERIALS RM ON SP.MATERIAL_SRNO = RM.MATERIAL_SRNO
        INNER JOIN M_STATUS MS ON SP.STATUS_SRNO = MS.STATUS_SRNO
        INNER JOIN M_VENDORS MV ON SP.C_LOCATION = MV.VENDOR_SRNO
        INNER JOIN M_GRADE MG ON RM.MATERIAL_GRADE_SRNO = MG.GRADE_SRNO
        INNER JOIN M_THICKNESS MT ON RM.MATERIAL_THICKNESS_SRNO = MT.THICKNESS_SRNO
        --CROSS APPLY (SELECT dbo.FN_GET_SLITTED_WIDTH(0, SP.SLITTING_SRNO) AS SLITTED_WIDTH) AS FN
		CROSS APPLY dbo.FN_GET_SLITTED_DATA(0, SP.SLITTING_SRNO) AS FN
        WHERE 
            SP.DEL_FLAG = 0
            AND RM.DEL_FLAG = 0
            AND (RM.MATERIAL_GRADE_SRNO = @GRADE_SRNO)
            AND (RM.MATERIAL_THICKNESS_SRNO = @THICKNESS_SRNO)
            --AND (@C_LOCATION IS NULL OR SP.C_LOCATION = @C_LOCATION)
            AND SP.STATUS_SRNO IN (4,5,8)
            AND ((SP.SLITTING_WIDTH - ISNULL(FN.SLITTED_WIDTH, 0) - ISNULL(SP.SLITTING_SCRAP, 0)) BETWEEN (@RequiredWidth - @WIDTH_VARIATION) AND (@RequiredWidth + @WIDTH_VARIATION))
                



-- Return Detailed Data
SELECT 
			--CHALLAN_NO,
			C_LOCATION,
			BALANCE_WEIGHT,
			BALANCE_WIDTH,
			GRADE,
			THICKNESS,
			STATUS_NAME,
			COIL_TYPE_FLAG,
			STRING_AGG(SLITTING_SRNO, ',') AS SLITTING_SRNOS, 
			STRING_AGG(MATERIAL_SRNO, ',') AS MATERIAL_SRNOS, 
			COUNT(DISTINCT CASE WHEN COIL_TYPE_FLAG IN ('S', 'P') THEN SLITTING_SRNO ELSE MATERIAL_SRNO END) AS QUANTITY,
			CASE 
				WHEN COIL_TYPE_FLAG = 'S' THEN 'Slitted Coil' 
				WHEN COIL_TYPE_FLAG = 'P' THEN 'Semi Slitted Coil' 
				ELSE 'Mother Coil'
			END AS COIL_TYPE
		FROM @TempResult
		GROUP BY C_LOCATION, BALANCE_WEIGHT, BALANCE_WIDTH, GRADE, THICKNESS, STATUS_NAME, COIL_TYPE_FLAG;





	------------------------------------------------
	--T3 - TOTAL WEIGHT REQUREID AND PRICING PARAMTER 
	--CALCULATE PIPE WEIGHT START
	DECLARE @PR_WEIGHT DECIMAL(18,2) = 0, @PR_TOTAL_WEIGHT DECIMAL(18,2) = 0
	SELECT @PR_WEIGHT  = 
    ((CAST(@OD AS FLOAT) - CAST(@THICKNESS AS FLOAT)) * 
     CAST(@THICKNESS AS FLOAT) * 
     CAST(@PR_LENGTH AS FLOAT) * 0.00002485);

	 SET @PR_TOTAL_WEIGHT = @PR_WEIGHT * @PR_QUANTITY
   --CALCULATE PIPE WEIGHT END

   -- pricing Calculation
   DECLARE @PR_TOTAL_PRICE DECIMAL(18,2) = 0
   SET @PR_TOTAL_PRICE = @PR_PRICE * @PR_TOTAL_WEIGHT
   --- pricing calculation end


  -- SET @PR_TOTAL_WEIGHT = @PR_WEIGHT * @PR_QUANTITY
	 DECLARE @ksh NUMERIC(10,2)
	 SELECT @ksh  = dbo.FN_CALCULATE_PIPE_WEIGHT_BY_VALUES(@OD, @THICKNESS, @PR_LENGTH, 0.02485, 1);


   --select t3 start
   SELECT 'Weight' AS section, 'Weight' AS label, CAST(@PR_WEIGHT AS VARCHAR) AS value
	UNION ALL
	SELECT 'Weight', 'Total Weight', CAST(@PR_TOTAL_WEIGHT AS VARCHAR)
	UNION ALL
	SELECT 'Price', 'Price', CAST(@PR_PRICE AS VARCHAR)
	UNION ALL
	SELECT 'Price', 'Total Price', CAST(@PR_TOTAL_PRICE AS VARCHAR)
	UNION ALL
	SELECT 'Width', 'Required Coil Width', CAST(@RequiredWidth AS VARCHAR)
	UNION ALL
	SELECT 'khs', 'Required Coil Width', CAST(@ksh AS VARCHAR);


	
   --select t3 end

		
END;
GO

-- Create function to calculate pipe weight
USE [OMECH_PROD]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FN_CALCULATE_PIPE_WEIGHT_BY_VALUES]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
    DROP FUNCTION [dbo].[FN_CALCULATE_PIPE_WEIGHT_BY_VALUES]
GO

CREATE FUNCTION [dbo].[FN_CALCULATE_PIPE_WEIGHT_BY_VALUES]
(
    @OD DECIMAL(18,2),
    @THICKNESS DECIMAL(18,2),
    @LENGTH DECIMAL(18,2),
    @FACTOR DECIMAL(18,5),
    @QUANTITY INT
)
RETURNS DECIMAL(18,2)
AS
BEGIN
    DECLARE @WEIGHT DECIMAL(18,2);
    
    SET @WEIGHT = ((@OD - @THICKNESS) * @THICKNESS * @LENGTH * @FACTOR) * @QUANTITY;
    
    RETURN @WEIGHT;
END;
GO
