USE [OMECH_PROD]
GO
/****** Object:  StoredProcedure [dbo].[DISP_PO_AUTO_MAP]    Script Date: 06-08-2025 05:32:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- DISP_PO_AUTO_MAP NULL,2,6,7
ALTER PROCEDURE [dbo].[DISP_PO_AUTO_MAP]
    @SCHEDULE_SRNOS NVARCHAR(MAX) = NULL,
	@GRADE_SRNO INT = NULL,
    @THICKNESS_SRNO INT = NULL,
    @OD_SRNO INT = NULL,
    @PARTY_NAME NVARCHAR(100) = NULL,
    @PO_NUMBER NVARCHAR(100) = NULL,
    @ENTRY_DATE_FROM DATE = NULL,
    @ENTRY_DATE_TO DATE = NULL,
    @DELIVERY_DATE_FROM DATE = NULL,
    @DELIVERY_DATE_TO DATE = NULL,
    @USER_SRNO INT = NULL
AS
BEGIN
-- Create a temporary table to hold the schedule serial numbers
    DECLARE @TempScheduleSrnos TABLE (SCHEDULE_SRNO INT);
    
    -- Parse the comma-separated list of SCHEDULE_SRNOS
    INSERT INTO @TempScheduleSrnos (SCHEDULE_SRNO)
    SELECT value FROM STRING_SPLIT(@SCHEDULE_SRNOS, ',');
    
    -- Group POs by thickness, grade, and OD
    SELECT 
        G.GRADE,
        G.GRADE_SRNO,
        T.THICKNESS,
        T.THICKNESS_SRNO,
        O.OD,
        O.OD_SRNO,
        SM.ITEM_TYPE,
		SM.PARTY_NAME,
		SM.PO_NUMBER,
		SUM(CASE WHEN SM.ITEM_TYPE = 'PIPE' THEN ISNULL(SD.QUANTITY, 0) ELSE 0 END) AS PIPE_QTY,
        SUM(CASE WHEN SM.ITEM_TYPE IN ('COIL', 'SHEET') THEN ISNULL(SD.WEIGHT_KG, 0) ELSE ISNULL(SD.WEIGHT_PER_QTY, 0) * SD.QUANTITY END) AS COIL_SHEET_WEIGHT,
        STRING_AGG(CAST(SD.LENGTH AS VARCHAR), ',') AS LENGTH,
        STRING_AGG(CAST(SM.SCHEDULE_SRNO AS VARCHAR), ',') AS SCHEDULE_SRNOS,
        STRING_AGG(CAST(SD.SCHEDULE_DT_SRNO AS VARCHAR), ',') AS SCHEDULE_DT_SRNOS
    FROM SCHEDULE_DETAIL SD
    INNER JOIN SCHEDULE_MASTER SM ON SD.SCHEDULE_SRNO = SM.SCHEDULE_SRNO
    INNER JOIN M_GRADE G ON SD.GRADE_SRNO = G.GRADE_SRNO
    INNER JOIN M_THICKNESS T ON SD.THICKNESS_SRNO = T.THICKNESS_SRNO
    LEFT JOIN M_OD O ON SD.OD_SRNO = O.OD_SRNO
    WHERE 
        SD.DEL_FLAG = 0 AND SM.DEL_FLAG = 0
		AND SD.STATUS_SRNO = 11 --AND SM.STATUS_SRNO = 11 
        AND (@SCHEDULE_SRNOS IS NULL OR SM.SCHEDULE_SRNO IN (SELECT SCHEDULE_SRNO FROM @TempScheduleSrnos))
		AND (@GRADE_SRNO IS NULL OR SD.GRADE_SRNO = @GRADE_SRNO)
		AND (@THICKNESS_SRNO IS NULL OR SD.THICKNESS_SRNO = @THICKNESS_SRNO)
		AND (@OD_SRNO IS NULL OR SD.OD_SRNO = @OD_SRNO)
		AND (@PARTY_NAME IS NULL OR SM.PARTY_NAME LIKE '%' + @PARTY_NAME + '%')
		AND (@PO_NUMBER IS NULL OR SM.PO_NUMBER LIKE '%' + @PO_NUMBER + '%')
		AND (@ENTRY_DATE_FROM IS NULL OR SM.SCHEDULE_DATE >= @ENTRY_DATE_FROM)
		AND (@ENTRY_DATE_TO IS NULL OR SM.SCHEDULE_DATE <= @ENTRY_DATE_TO)
		AND (@DELIVERY_DATE_FROM IS NULL OR SM.ESTIMATED_DELIVERY_DATE >= @DELIVERY_DATE_FROM)
		AND (@DELIVERY_DATE_TO IS NULL OR SM.ESTIMATED_DELIVERY_DATE <= @DELIVERY_DATE_TO)
        --AND SD.STATUS_SRO = 11 -- Pending status
    GROUP BY 
        G.GRADE,
        G.GRADE_SRNO,
        T.THICKNESS,
        T.THICKNESS_SRNO,
        O.OD,
        O.OD_SRNO,
        SM.ITEM_TYPE,
		SM.PARTY_NAME,
		SM.PO_NUMBER
    HAVING 
        COUNT(*) > 0;
	 END
